# Generated by Django 5.0.4 on 2024-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redisApp', '0002_group_chat_message_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_chat_message',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
