# Generated by Django 5.0.4 on 2024-04-25 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redisApp', '0003_alter_group_chat_message_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_chat_message',
            name='channel_layer',
        ),
        migrations.AddField(
            model_name='group_chat_message',
            name='current_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
